### ISSUE TITLE
Check failed: err == CUBLAS_STATUS_SUCCESS (1 vs. 0) : Create cublas handle failed

### ISSUE THREAD

**Issue by edwardelric1202** [awslabs/sockeye#897]
When I use sockeye 2.2.0 with mxnet-cu101 1.7.0, I found a error when I tried to train, here is the error massage:
`[INFO:sockeye.train] Adjusting maximum length to reserve space for a BOS/EOS marker. New maximum length: (201, 201)
[INFO:sockeye.utils] Attempting to acquire 2 GPUs of 4 GPUs. The requested devices are: [0, 1]
[INFO:sockeye.utils] Acquired GPU master_lock.
[INFO:sockeye.utils] Acquired GPU 0.
[INFO:sockeye.utils] Acquired GPU 1.
[INFO:sockeye.utils] Releasing GPU master_lock.
[INFO:sockeye.train] Training Device(s): gpu(0), gpu(1)
[INFO:sockeye.utils] Random seed: 1
terminate called after throwing an instance of 'dmlc::Error'
  what():  [18:47:35] /home/centos/mxnet/3rdparty/mshadow/mshadow/./stream_gpu-inl.h:134: Check failed: err == CUBLAS_STATUS_SUCCESS (1 vs. 0) : Create cublas handle failed`

my training args:
`sockeye-train --device-ids 0 1 \
--source $DATA/LDC_zhen.tc.zh.shuf \
--target $DATA/LDC_zhen.tc.en.shuf \
--max-seq-len 200:200 \
--shared-vocab --num-words 32000:32000 \
--validation-source $DATA/valid_bpe_32k.zh --validation-target $DATA/valid_bpe_32k.en.0 \
--output model \
--encoder transformer --decoder transformer --num-layers 6:6 --num-embed 512:512 \
--transformer-model-size 512 --transformer-attention-heads 8 --transformer-feed-forward-num-hidden 2048 \
--transformer-dropout-attention 0 --transformer-dropout-act 0 --transformer-dropout-prepost 0.1 --label-smoothing 0.1 \
--weight-init xavier --weight-init-scale 3.0 --weight-init-xavier-factor-type avg \
--gradient-clipping-threshold -1 \
--initial-learning-rate 0.0003 --batch-type word --batch-size 2048 \
--learning-rate-warmup 8000 \
--optimizer adam --optimized-metric bleu \
--checkpoint-interval 5000 --max-num-checkpoint-not-improved 20 --decode-and-evaluate 500 --keep-last-params 60 \
2>&1 | tee train.log`

How can I solve this? Hope for your answer.

**Comment by tdomhan** [comment]
Unfortunately it seems like there is an issue with the CUDA setup so that it will be difficult to give advice from a Sockeye perspective. 
What driver version are you using? I would check the nvidia driver and cuda setup.

**Comment by edwardelric1202** [comment]
> Unfortunately it seems like there is an issue with the CUDA setup so that it will be difficult to give advice from a Sockeye perspective.
> What driver version are you using? I would check the nvidia driver and cuda setup.

The CUDA version is 10.1 and driver version is 430.64.

**Comment by bricksdont** [comment]
I am seeing an error I think could be related, and is produced by code that used to work fine:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/sockeye/train.py", line 1013, in <module>
    main()
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/sockeye/train.py", line 776, in main
    train(args)
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/sockeye/train.py", line 859, in train
    utils.seed_rngs(args.seed, ctx=context)
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/sockeye/utils.py", line 125, in seed_rngs
    mx.random.seed(seed + i, ctx=c)
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/random.py", line 100, in seed
    check_call(_LIB.MXRandomSeedContext(seed_state, ctx.device_typeid, ctx.device_id))
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/base.py", line 255, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [13:24:15] /home/ubuntu/mxnet-distro/mxnet-build/3rdparty/mshadow/mshadow/./random.h:502: Check failed: status == CURAND_STATUS_SUCCESS (203 vs. 0) : Cannot create CURAND Generator
Stack trace:
  [bt] (0) /net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/libmxnet.so(+0x6d554b) [0x7f539362154b]
  [bt] (1) /net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/libmxnet.so(+0x41b734c) [0x7f539710334c]
  [bt] (2) /net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/libmxnet.so(+0x41b7f8b) [0x7f5397103f8b]
  [bt] (3) /net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/libmxnet.so(+0x41b8be2) [0x7f5397104be2]
  [bt] (4) /net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/libmxnet.so(+0x41b9dd5) [0x7f5397105dd5]
  [bt] (5) /net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/libmxnet.so(MXRandomSeedContext+0x3a) [0x7f539674670a]
  [bt] (6) /net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7f53dcfbae20]
  [bt] (7) /net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call+0x2eb) [0x7f53dcfba88b]
  [bt] (8) /net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(_ctypes_callproc+0x49a) [0x7f53dcfb501a]
```

Versions:

```
[INFO:sockeye.utils] Sockeye version 2.1.17, commit 92a020a25cbe75935c700ce2f29b286b31a87189, path /net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/sockeye/__init__.py
[INFO:sockeye.utils] MXNet version 1.6.0, path /net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/__init__.py
```

CUDA and driver versions:

    NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2

**Comment by bricksdont** [comment]
Update: I resolved my issue by making the model smaller (in particular, cutting the vocabulary size in half). The error about creating CURAND seems to be due to GPU out-of-memory,

it would be worth checking if `Create cublas handle failed` can also be avoided with a smaller number of parameters.

**Comment by tdomhan** [comment]
Interesting! Would definitely be worth trying to reduce memory in that case just to see whether that resolved the problem. The easiest way is probably through `--batch-size`.

**Comment by bricksdont** [comment]
Just wanted to post a quick update here:

Over the last weeks I have seen countless error messages all related to CUDNN, CUDA, CURAND, CUBLAS and so on. Even though the actual error thrown is different, the underlying reason is in fact always OOM on GPU.

I would be confident that this issue can be closed.
